server:
  port: 7701

#not used because we are not connecting to database
#using our own database so named as secondDatasource
#spring:
  #secondDatasource:
    #url: jdbc:mysql://localhost:3306/testDb?autoReconnect=true&useSSL=false
    #username: testDb
    #password: testDb    